update script for ubuntu

diff --git a/paxos/verify b/paxos/verify
--- a/paxos/verify
+++ b/paxos/verify
@@ -1,8 +1,19 @@
 #!/bin/bash -li
 
-dafny="/usr/local/lib/dafny/dafny /timeLimit:20 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:3"
-dafnylong="/usr/local/lib/dafny/dafny /timeLimit:40 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:3"
+if uname -a | grep -q Darwin; then
 
+    dafny="/usr/local/lib/dafny/dafny /timeLimit:20 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:4"
+    dafnylong="/usr/local/lib/dafny/dafny /timeLimit:40 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:4"
+
+elif uname -a | grep -q Linux; then
+
+    dafny="/usr/lib/dafny3/dafny /timeLimit:20 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:4"
+    dafnylong="/usr/lib/dafny3/dafny /timeLimit:40 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:4"
+
+else
+    echo "Verification failed"
+    exit 1
+fi
 
 ### Definition Files 
 echo ""
@@ -32,4 +43,3 @@ echo "Verifying proof_agreement.dfy"
 $dafny proof_agreement.dfy
 
 echo "Done"
-
